// ════════════════════════════════════════════════════════════════════
//   Wizard reference data — kept in its own module so the React
//   component file stays compact. Sourced from the 2024 PHB plus the
//   user's homebrew background PDF. Feature progressions cover levels
//   1–20 with the headline ability granted at each level.
// ════════════════════════════════════════════════════════════════════

export const SPECIES_LIST = [
  "Aasimar", "Aatrocias", "Changeling", "Dragonborn", "Dwarf", "Elf",
  "Genasi", "Goblin", "Golem", "Goliath", "Half-Elf", "Halfling",
  "Human", "Leonin", "Orc", "Shadowborn", "Tabaxi", "Tiefling",
  "Triton", "Undead", "Voltarin", "Warforged",
];

// Per-species traits surfaced in the wizard's preview card. Kept short —
// the full text lives in the sheet's Features tab once a character is
// created. Vision: "Normal" or "Darkvision N ft".
//
// `art` → filename under `/race-art/` rendered as the headline portrait.
// `subraces` → optional array of subrace records; each subrace has its
//              own `art` (and may have a `traits` override). Used by
//              Elf, Genasi, and Warforged for now.
export const SPECIES_INFO = {
  Aasimar:    { art: "aasimar.png",    size: "Medium", speed: 30, vision: "Darkvision 60 ft", flavor: "Touched by the upper planes, marked with celestial light, struggling between mortal life and divine purpose.", traits: ["Celestial Resistance (necrotic & radiant)", "Healing Hands (1d4 × level once per Long Rest)", "Light cantrip known", "Celestial Revelation at lvl 3"] },
  Aatrocias:  { art: "aatrocias.png",  size: "Medium", speed: 30, vision: "Darkvision 60 ft", flavor: "Homebrew lineage tied to the user's world. See the Features tab once created for full racial traits.", traits: ["Custom homebrew lineage — see Features tab"] },
  Changeling: { art: "changeling.png", size: "Medium", speed: 30, vision: "Normal",          flavor: "Faceless shapeshifters of unknown origin, drifting between identities like masks at a ball.", traits: ["Shapechanger — alter your appearance as an action", "Changeling Instincts (proficiency in 2 chosen social skills)", "Two extra languages"] },
  Dragonborn: { art: "dragonborn.png", size: "Medium", speed: 30, vision: "Normal",          flavor: "Scaled descendants of dragons, marked by their heritage in colour, breath, and pride.", traits: ["Draconic Ancestry (chosen damage type)", "Breath Weapon (replace one attack, 1d10 dmg)", "Damage Resistance to ancestral type", "Draconic Flight at lvl 5"] },
  Dwarf:      { art: "dwarf.png",      size: "Medium", speed: 30, vision: "Darkvision 120 ft", flavor: "Hardy folk of stone and forge, with grudges as long as their beards.", traits: ["Dwarven Resilience (advantage vs. poison, resistance)", "Dwarven Toughness (+1 HP/level)", "Stonecunning (Tremorsense 60 ft for 10 min as bonus action)"] },
  Elf:        {
    art: "elf.jpg",
    size: "Medium", speed: 30, vision: "Darkvision 60 ft",
    flavor: "Long-lived folk of grace and magic; their memory threads centuries.",
    traits: ["Trance (4-hour rest)", "Fey Ancestry (advantage vs. charm, no magical sleep)", "Keen Senses (proficiency in Insight, Perception, or Survival)"],
    subraces: [
      { name: "Drow",     art: "elf-drow.jpg",  traits: ["Superior Darkvision 120 ft", "Drow Magic — Dancing Lights cantrip; Faerie Fire at 3; Darkness at 5", "Sunlight Sensitivity (disadvantage in direct sunlight)"] },
      { name: "High Elf", art: "elf-high.jpg",  traits: ["Cantrip from the Wizard list", "+1 INT or DEX recommended", "Extra language of your choice"] },
      { name: "Moon Elf", art: "elf-moon.jpg",  traits: ["Faerie Step — Misty Step at higher levels", "Charm immunity (full)", "Affinity for night & shadow"] },
      { name: "Wood Elf", art: "elf-wood.jpg",  traits: ["Mask of the Wild (hide when lightly obscured)", "Fleet of Foot (+5 ft walking speed)", "Druidcraft cantrip"] },
    ],
  },
  Genasi:     {
    art: "genasi.jpg",
    size: "Medium", speed: 30, vision: "Darkvision 60 ft",
    flavor: "Mortals of the inner planes — air, earth, fire, or water given flesh.",
    traits: ["Reach Beyond — innate elemental cantrip", "Elemental Resistance based on heritage"],
    subraces: [
      { name: "Air",   art: "genasi-air.jpg",   traits: ["Unending Breath (no need to breathe)", "Mingle with the Wind — Levitate (CHA), prof bonus per Long Rest", "Lightning resistance"] },
      { name: "Earth", art: "genasi-earth.jpg", traits: ["Earth Walk (move through difficult earth terrain unhindered)", "Merge with Stone — Blade Ward cantrip; Pass Without Trace later", "Thunder resistance"] },
      { name: "Fire",  art: "genasi-fire.jpg",  traits: ["Darkvision 120 ft", "Reach to the Blaze — Produce Flame; Burning Hands later", "Fire resistance"] },
      { name: "Water", art: "genasi-water.jpg", traits: ["Swim speed 30 ft", "Reach to the River — Shape Water cantrip; Create or Destroy Water later", "Acid resistance"] },
    ],
  },
  Goblin:     { art: "goblin.jpg",     size: "Small",  speed: 30, vision: "Darkvision 60 ft", flavor: "Wiry, cunning survivors who turn every defeat into a darting escape.", traits: ["Fury of the Small (extra damage 1/turn = prof bonus)", "Nimble Escape (Disengage or Hide as bonus action)", "Fey heritage — advantage vs. charm"] },
  Golem:      { art: "golem.png",      size: "Medium", speed: 30, vision: "Darkvision 60 ft", flavor: "Constructed beings of clay, iron, or sterner stuff. Built with purpose, animated with will.", traits: ["Constructed Resilience (no need to eat/sleep, immune to disease)", "Sentry's Rest (alert during Long Rest)", "Repair via mending or Long Rest"] },
  Goliath:    { art: "goliath.png",    size: "Medium", speed: 35, vision: "Normal",          flavor: "Mountain-touched giants in mortal frame. Stoic, competitive, proud.", traits: ["Giant Ancestry (8 lineage options with unique boons)", "Powerful Build (count as Large for carry/push)", "Large Form at lvl 5"] },
  "Half-Elf": { art: "half-elf.jpg",   size: "Medium", speed: 30, vision: "Darkvision 60 ft", flavor: "Born of two worlds, fitting neatly into neither, but moving freely between both.", traits: ["+2 to one ability, +1 to two others", "Fey Ancestry (advantage vs. charm)", "Skill Versatility (proficiency in 2 chosen skills)"] },
  Halfling:   { art: "halfling.jpg",   size: "Small",  speed: 30, vision: "Normal",          flavor: "Cheery folk of hearth and road, small in stature but vast in luck.", traits: ["Lucky (reroll natural 1s on attacks/abilities/saves)", "Brave (advantage vs. frightened)", "Halfling Nimbleness (move through larger creatures' spaces)"] },
  Human:      { art: "human.jpg",      size: "Medium", speed: 30, vision: "Normal",          flavor: "Adaptable, ambitious, and everywhere — humans shape every corner of the world.", traits: ["Resourceful (1 free Heroic Inspiration after every Long Rest)", "Skillful (one extra skill proficiency)", "Versatile (one Origin Feat at lvl 1)"] },
  Leonin:     { art: "leonin.jpg",     size: "Medium", speed: 35, vision: "Darkvision 60 ft", flavor: "Lion-like nomads of the savanna. Honour, pride, and the joy of the hunt.", traits: ["Daunting Roar (frighten adjacent creatures, bonus action)", "Hunter's Instincts (Perception proficiency)", "Powerful Build"] },
  Orc:        { art: "orc.jpg",        size: "Medium", speed: 30, vision: "Darkvision 120 ft", flavor: "Tireless warriors of fierce devotion to clan, code, and the long road.", traits: ["Adrenaline Rush (Dash as bonus action = prof bonus uses per Long Rest)", "Powerful Build", "Relentless Endurance (drop to 1 HP instead of 0, 1×Long Rest)"] },
  Shadowborn: { art: "shadowborn.jpg", size: "Medium", speed: 30, vision: "Darkvision 120 ft", flavor: "Homebrew — children of the shadow realms, with strange and quiet powers.", traits: ["Custom homebrew lineage — see Features tab"] },
  Tabaxi:     { art: "tabaxi.jpg",     size: "Medium", speed: 30, vision: "Darkvision 60 ft", flavor: "Curious feline wanderers — agile, clever, and forever chasing the next horizon.", traits: ["Feline Agility (double speed on your turn, refreshes after no-movement turn)", "Cat's Claws (climb speed 20 ft, claws as natural weapons)", "Cat's Talent (Perception & Stealth proficiency)"] },
  Tiefling:   { art: "tiefling.png",   size: "Medium", speed: 30, vision: "Darkvision 60 ft", flavor: "Mortals marked by infernal heritage. Suspicion follows; ambition burns.", traits: ["Fiendish Legacy (pick Abyssal / Chthonic / Infernal sub-list)", "Damage Resistance per legacy", "Thaumaturgy cantrip + 1 spell at lvl 3 + 1 at lvl 5"] },
  Triton:     { art: "triton.jpg",     size: "Medium", speed: 30, vision: "Darkvision 60 ft", flavor: "Guardians of the deep, surfaced to defend the sea-touched lands above.", traits: ["Amphibious + swim speed 30 ft", "Control Air & Water (Fog Cloud at 1, Gust of Wind at 3, Water Walk at 5)", "Cold resistance", "Emissary of the Sea (speak to water-breathing creatures)"] },
  Undead:     { art: "undead.png",     size: "Medium", speed: 30, vision: "Darkvision 120 ft", flavor: "Animated by lingering will, neither truly alive nor at rest.", traits: ["Undead Nature (immune to disease & poison, no need to breathe)", "Resistance to necrotic damage", "Sentry's Rest"] },
  Voltarin:   { art: "voltarin.jpg",   size: "Medium", speed: 30, vision: "Darkvision 60 ft", flavor: "Homebrew lineage charged with crackling energy. Storms answer their call.", traits: ["Custom homebrew lineage — see Features tab"] },
  Warforged:  {
    art: "warforged.jpg",
    size: "Medium", speed: 30, vision: "Normal",
    flavor: "Sentient constructs forged for a war that has ended — but the soldier remembers.",
    traits: ["Constructed Resilience (no food/sleep, immune to disease & poison)", "Integrated Protection (+1 AC, armor cannot be removed)", "Sentry's Rest"],
    subraces: [
      { name: "Porcelain", art: "warforged-porcelain.jpg", traits: ["Refined shell — advantage on social-impression rolls", "Specialised Design (one extra skill + tool proficiency)"] },
      { name: "Steel",     art: "warforged-steel.jpg",     traits: ["Reinforced plating (+1 AC stacks with armor)", "Specialised Design (one extra skill + tool proficiency)"] },
    ],
  },
};

export const CLASS_LIST = [
  "Artificer", "Barbarian", "Bard", "Cleric", "Druid", "Fighter",
  "Monk", "Paladin", "Ranger", "Rogue", "Sorcerer", "Warlock", "Wizard",
  "Omni-Knight",
];

// Per-class meta + full 20-level feature progression. ASI = "Ability
// Score Improvement (or feat)" granted at most level milestones. Empty
// arrays mean "no new feature this level" and the wizard will collapse
// them visually.
function asi(level) { return [`Ability Score Improvement (lvl ${level})`]; }

export const CLASS_INFO = {
  Artificer: {
    hitDie: "d8", primary: "INT", saves: "CON & INT", caster: "Half (INT)",
    armor: "Light, Medium, Shields", weapons: "Simple weapons, firearms",
    flavor: "Tinker-engineers who infuse magic into mundane gear. Combine arcane theory with a workshop, a wrench, and a wild imagination.",
    tagline: "The artificer of magic and machine.",
    features: {
      1: ["Spellcasting (INT)", "Magical Tinkering"],
      2: ["Infuse Item (2 infusions, 2 known)"],
      3: ["Artificer Specialist subclass", "Specialist feature"],
      4: asi(4),
      5: ["Specialist feature"],
      6: ["Tool Expertise"],
      7: ["Flash of Genius"],
      8: asi(8),
      9: ["Specialist feature"],
      10: ["Magic Item Adept"],
      11: ["Spell-Storing Item"],
      12: asi(12),
      13: [],
      14: ["Magic Item Savant"],
      15: ["Specialist feature"],
      16: asi(16),
      17: [],
      18: ["Magic Item Master"],
      19: asi(19),
      20: ["Soul of Artifice (+1 saves per infusion, drop to 1 HP 1×Long Rest)"],
    },
  },
  Barbarian: {
    hitDie: "d12", primary: "STR", saves: "STR & CON", caster: "None",
    armor: "Light, Medium, Shields", weapons: "Simple & Martial",
    flavor: "Rage-fuelled warriors who weather punishment most heroes can't imagine — and answer in kind.",
    tagline: "The fury of the wild made flesh.",
    features: {
      1: ["Rage (2 uses)", "Unarmored Defense", "Weapon Mastery (2)"],
      2: ["Danger Sense", "Reckless Attack"],
      3: ["Primal Path subclass", "Primal Knowledge"],
      4: asi(4),
      5: ["Extra Attack", "Fast Movement"],
      6: ["Path feature"],
      7: ["Feral Instinct", "Instinctive Pounce"],
      8: asi(8),
      9: ["Brutal Strike"],
      10: ["Path feature"],
      11: ["Relentless Rage"],
      12: asi(12),
      13: ["Improved Brutal Strike"],
      14: ["Path feature"],
      15: ["Persistent Rage"],
      16: asi(16),
      17: ["Brutal Strike Mastery"],
      18: ["Indomitable Might"],
      19: asi(19),
      20: ["Primal Champion (+4 STR & CON, max 25)"],
    },
  },
  Bard: {
    hitDie: "d8", primary: "CHA", saves: "DEX & CHA", caster: "Full (CHA)",
    armor: "Light", weapons: "Simple, hand crossbow, longsword, rapier, shortsword",
    flavor: "Charismatic performers who weave reality with song, story, and a touch of swagger.",
    tagline: "The voice that shapes the world.",
    features: {
      1: ["Spellcasting (CHA)", "Bardic Inspiration (d6)"],
      2: ["Expertise (2)", "Jack of All Trades"],
      3: ["Bard College subclass"],
      4: asi(4),
      5: ["Font of Inspiration (Short Rest)", "Bardic Inspiration d8"],
      6: ["College feature"],
      7: ["Countercharm"],
      8: asi(8),
      9: ["Expertise (2 more)"],
      10: ["Magical Secrets (2)", "Bardic Inspiration d10"],
      11: [],
      12: asi(12),
      13: ["Magical Secrets (1)"],
      14: ["College feature"],
      15: ["Bardic Inspiration d12"],
      16: asi(16),
      17: ["Magical Secrets (1)"],
      18: ["Superior Inspiration"],
      19: asi(19),
      20: ["Words of Creation (Power Word Heal)"],
    },
  },
  Cleric: {
    hitDie: "d8", primary: "WIS", saves: "WIS & CHA", caster: "Full (WIS)",
    armor: "Light, Medium, Shields", weapons: "Simple",
    flavor: "Conduits of divine will. Healers, smiters, and shields of the faithful in one body.",
    tagline: "The hand of the divine.",
    features: {
      1: ["Spellcasting (WIS)", "Divine Order (Protector or Thaumaturge)"],
      2: ["Channel Divinity (Divine Spark + Turn Undead)"],
      3: ["Divine Domain subclass"],
      4: asi(4),
      5: ["Sear Undead (via Channel Divinity)"],
      6: ["Domain feature"],
      7: ["Blessed Strikes"],
      8: asi(8),
      9: [],
      10: ["Divine Intervention"],
      11: [],
      12: asi(12),
      13: [],
      14: ["Improved Blessed Strikes"],
      15: [],
      16: asi(16),
      17: ["Domain feature"],
      18: [],
      19: asi(19),
      20: ["Greater Divine Intervention (call your god, 7-day cooldown)"],
    },
  },
  Druid: {
    hitDie: "d8", primary: "WIS", saves: "INT & WIS", caster: "Full (WIS)",
    armor: "Light, Medium, Shields (non-metal)", weapons: "Simple",
    flavor: "Primal spellcasters bonded to nature — shapeshifters, weather-callers, and beast-tongues.",
    tagline: "The voice of the wild places.",
    features: {
      1: ["Spellcasting (WIS)", "Druidic language", "Primal Order"],
      2: ["Wild Companion / Wild Shape"],
      3: ["Druid Circle subclass"],
      4: ["Cantrip Versatility", ...asi(4)],
      5: [],
      6: ["Circle feature"],
      7: ["Elemental Fury"],
      8: asi(8),
      9: [],
      10: ["Circle feature"],
      11: [],
      12: asi(12),
      13: [],
      14: ["Circle feature"],
      15: ["Improved Elemental Fury"],
      16: asi(16),
      17: [],
      18: ["Beast Spells (cast in Wild Shape)"],
      19: asi(19),
      20: ["Archdruid (unlimited Wild Shape, immortal aging)"],
    },
  },
  Fighter: {
    hitDie: "d10", primary: "STR or DEX", saves: "STR & CON", caster: "None",
    armor: "All armor, Shields", weapons: "Simple & Martial",
    flavor: "Masters of weapons, armour, and battlefield discipline. Adaptable in any fight.",
    tagline: "The blade for every battle.",
    features: {
      1: ["Fighting Style", "Second Wind", "Weapon Mastery (3)"],
      2: ["Action Surge", "Tactical Mind"],
      3: ["Martial Archetype subclass"],
      4: asi(4),
      5: ["Extra Attack"],
      6: asi(6),
      7: ["Archetype feature"],
      8: asi(8),
      9: ["Indomitable", "Tactical Shift"],
      10: ["Archetype feature"],
      11: ["Two Extra Attacks (3 total)"],
      12: asi(12),
      13: ["Studied Attacks"],
      14: asi(14),
      15: ["Archetype feature"],
      16: asi(16),
      17: ["Action Surge (2 uses)"],
      18: ["Archetype feature"],
      19: ["Epic Boon"],
      20: ["Three Extra Attacks (4 total)"],
    },
  },
  Monk: {
    hitDie: "d8", primary: "DEX & WIS", saves: "STR & DEX", caster: "None",
    armor: "None", weapons: "Simple & monk weapons",
    flavor: "Disciplined martial artists who channel inner ki into supernatural speed and grace.",
    tagline: "Body, mind, and breath as one weapon.",
    features: {
      1: ["Martial Arts (1d6)", "Unarmored Defense (DEX + WIS)"],
      2: ["Monk's Discipline (Flurry/Patient Defense/Step of the Wind)", "Unarmored Movement +10"],
      3: ["Monastic Order subclass", "Deflect Attacks"],
      4: ["Slow Fall", ...asi(4)],
      5: ["Extra Attack", "Stunning Strike"],
      6: ["Empowered Strikes", "Order feature"],
      7: ["Evasion", "Stillness of Mind"],
      8: asi(8),
      9: ["Acrobatic Movement"],
      10: ["Heightened Focus", "Self-Restoration"],
      11: ["Order feature"],
      12: asi(12),
      13: ["Deflect Energy"],
      14: ["Disciplined Survivor"],
      15: ["Perfect Focus"],
      16: asi(16),
      17: ["Order feature"],
      18: ["Empty Body (Invisibility for 1 min)"],
      19: ["Epic Boon"],
      20: ["Body and Mind (+4 DEX & WIS, max 25)"],
    },
  },
  Paladin: {
    hitDie: "d10", primary: "STR & CHA", saves: "WIS & CHA", caster: "Half (CHA)",
    armor: "All armor, Shields", weapons: "Simple & Martial",
    flavor: "Oath-bound warriors of conviction — divine smites in one hand, chivalry in the other.",
    tagline: "The blade and the oath.",
    features: {
      1: ["Lay on Hands (5 × lvl HP pool)", "Spellcasting (CHA)", "Weapon Mastery (2)"],
      2: ["Fighting Style", "Divine Smite"],
      3: ["Sacred Oath subclass", "Channel Divinity"],
      4: asi(4),
      5: ["Extra Attack", "Faithful Steed"],
      6: ["Aura of Protection"],
      7: ["Oath feature"],
      8: asi(8),
      9: ["Abjure Foes"],
      10: ["Aura of Courage"],
      11: ["Radiant Strikes"],
      12: asi(12),
      13: [],
      14: ["Restoring Touch"],
      15: ["Oath feature"],
      16: asi(16),
      17: [],
      18: ["Aura Expansion (30 ft)"],
      19: ["Epic Boon"],
      20: ["Oath capstone"],
    },
  },
  Ranger: {
    hitDie: "d10", primary: "DEX & WIS", saves: "STR & DEX", caster: "Half (WIS)",
    armor: "Light, Medium, Shields", weapons: "Simple & Martial",
    flavor: "Wilderness-honed warriors who track foes and cast nature magic in equal measure.",
    tagline: "The hunt is your home.",
    features: {
      1: ["Favored Enemy", "Weapon Mastery (2)"],
      2: ["Deft Explorer", "Fighting Style", "Spellcasting (WIS)"],
      3: ["Ranger Conclave subclass", "Roving"],
      4: asi(4),
      5: ["Extra Attack"],
      6: ["Roving improvement", "Conclave feature"],
      7: ["Nature's Veil"],
      8: asi(8),
      9: [],
      10: ["Tireless"],
      11: ["Conclave feature"],
      12: asi(12),
      13: [],
      14: ["Nature's Veil (2 uses)"],
      15: ["Conclave feature"],
      16: asi(16),
      17: [],
      18: ["Feral Senses"],
      19: ["Epic Boon"],
      20: ["Foe Slayer (+ WIS to attacks/dmg of Favored Enemy)"],
    },
  },
  Rogue: {
    hitDie: "d8", primary: "DEX", saves: "DEX & INT", caster: "Subclass-dependent",
    armor: "Light", weapons: "Simple, hand crossbow, longsword, rapier, shortsword",
    flavor: "Stealth, finesse, and Sneak Attack — the masters of doing the most damage from the shadows.",
    tagline: "One strike from the dark.",
    features: {
      1: ["Expertise (2)", "Sneak Attack (1d6)", "Thieves' Cant", "Weapon Mastery (2)"],
      2: ["Cunning Action"],
      3: ["Roguish Archetype subclass", "Steady Aim"],
      4: asi(4),
      5: ["Cunning Strike", "Uncanny Dodge"],
      6: ["Expertise (2 more)"],
      7: ["Evasion", "Reliable Talent"],
      8: asi(8),
      9: ["Archetype feature"],
      10: ["Subtle Strikes"],
      11: ["Improved Cunning Strike"],
      12: asi(12),
      13: ["Archetype feature"],
      14: ["Devious Strikes"],
      15: ["Slippery Mind (proficiency in WIS saves)"],
      16: asi(16),
      17: ["Archetype feature"],
      18: ["Elusive (no advantage against you)"],
      19: ["Epic Boon"],
      20: ["Stroke of Luck (turn a miss into a hit 1×Short Rest)"],
    },
  },
  Sorcerer: {
    hitDie: "d6", primary: "CHA", saves: "CON & CHA", caster: "Full (CHA)",
    armor: "None", weapons: "Simple",
    flavor: "Innate casters whose magic seeps from their lineage. Twist spells with Metamagic.",
    tagline: "Magic in the blood.",
    features: {
      1: ["Spellcasting (CHA)", "Sorcerous Origin subclass", "Innate Sorcery"],
      2: ["Font of Magic (Sorcery Points)", "Metamagic (2 options)"],
      3: ["Metamagic + Origin feature"],
      4: asi(4),
      5: ["Sorcerous Restoration"],
      6: ["Origin feature"],
      7: ["Sorcery Incarnate (2 metamagic per spell)"],
      8: asi(8),
      9: [],
      10: ["Metamagic (1 more)"],
      11: [],
      12: asi(12),
      13: [],
      14: ["Origin feature"],
      15: [],
      16: asi(16),
      17: ["Metamagic (1 more)"],
      18: ["Origin feature"],
      19: ["Epic Boon"],
      20: ["Arcane Apotheosis (full Sorcery Points refresh on Short Rest)"],
    },
  },
  Warlock: {
    hitDie: "d8", primary: "CHA", saves: "WIS & CHA", caster: "Pact Magic (CHA)",
    armor: "Light", weapons: "Simple",
    flavor: "Pact-bound casters who borrow a patron's power. Short-rest spell slots, big invocations.",
    tagline: "The whispered bargain.",
    features: {
      1: ["Pact Magic (CHA)", "Eldritch Invocations (1)", "Otherworldly Patron subclass"],
      2: ["Magical Cunning (regain slots on Short Rest)", "Eldritch Invocations (3 total)"],
      3: ["Pact Boon (Blade / Chain / Tome / Talisman)"],
      4: asi(4),
      5: ["Invocation (5 total)"],
      6: ["Patron feature"],
      7: ["Invocation (6 total)"],
      8: asi(8),
      9: ["Contact Patron"],
      10: ["Patron feature"],
      11: ["Mystic Arcanum (6th level)"],
      12: asi(12),
      13: ["Mystic Arcanum (7th level)"],
      14: ["Patron feature"],
      15: ["Mystic Arcanum (8th level)"],
      16: asi(16),
      17: ["Mystic Arcanum (9th level)"],
      18: ["Invocation (8 total)"],
      19: ["Epic Boon"],
      20: ["Eldritch Master (Patron-granted ritual)"],
    },
  },
  Wizard: {
    hitDie: "d6", primary: "INT", saves: "INT & WIS", caster: "Full (INT)",
    armor: "None", weapons: "Simple",
    flavor: "Scholar-mages who write magic into spellbooks. The widest, deepest spell list in the game.",
    tagline: "Knowledge is the truest power.",
    features: {
      1: ["Spellcasting (INT)", "Ritual Adept", "Arcane Recovery"],
      2: ["Scholar (knowledge skill swap)"],
      3: ["Arcane Tradition subclass"],
      4: asi(4),
      5: ["Memorize Spell (swap one prepared spell on Short Rest)"],
      6: ["Tradition feature"],
      7: ["Cantrip Formulas"],
      8: asi(8),
      9: [],
      10: ["Tradition feature"],
      11: [],
      12: asi(12),
      13: [],
      14: ["Tradition feature"],
      15: [],
      16: asi(16),
      17: [],
      18: ["Spell Mastery (1st & 2nd-level mastered)"],
      19: ["Epic Boon"],
      20: ["Signature Spells (two 3rd-level spells once per Short Rest free)"],
    },
  },
  "Omni-Knight": {
    hitDie: "d10", primary: "CHA", saves: "CHA", caster: "None (homebrew)",
    armor: "Light, Medium", weapons: "Imaginary weapons (any non-firearm)",
    flavor: "Warriors who have answered the call. Not your ordinary knights — those who felt limited by mundane steel train to forge weapons of pure imagination, summoning blades, bows, and bulwarks from thought alone.",
    tagline: "Forge your destiny with the power of your imagination.",
    features: {
      1: [
        "Imaginary Weaponry — conjure any non-firearm weapon (light / medium / heavy); spectral damage matches the imagined form (+1 at lvl 5, +2 at lvl 11, +3 at lvl 15, +4 at lvl 19). Can absorb another weapon's stats at the cost of imaginary bonuses.",
        "Intuitive Protection — bonus action, gain 1d10 temp HP (1×Long Rest)",
        "Ammunition — endless conjured ammunition for ranged weapons; start each fight with 5 (+3 per Extra Attack); can be coated with poison/oils",
      ],
      2: [
        "Creative Attack — 1×Long Rest: advantage on attacks +1d6 damage; resist psychic for 1 round but cannot use reactions",
        "Spectral Companion — small familiar of any colour, treat as a familiar",
      ],
      3: [
        "Omni Archetype — at the Order of Omnipotence's Blade you may attack using INT instead of CHA (optional); unlocks bonus spell list",
        "Respected — known Trained Omni-Knights are treated as heroes (or feared) wherever they go",
        "Intuitive Blade — 1×Long Rest: declared before the attack roll, adds +1d6 damage; no action or bonus action required",
      ],
      4: ["Ability Score Improvement"],
      5: ["Extra Attack — one extra attack on the Attack action", "Imaginary Weapon becomes +1"],
      6: ["Ability Score Improvement"],
      7: ["Zamirth's Blast — every successful attack also rolls a 1d10 force/psychic ranged or melee blast (150 ft); attack/damage use CHA modifier"],
      8: ["Ability Score Improvement"],
      9: ["Creative Builder — imagine into being a 60-ft tall/wide phantasmal structure with 100 HP (not transparent)"],
      10: ["My Domain — action, create a 30-ft wide, 100-ft tall imagined area for 2 rounds; advantage on saves + one extra attack while inside"],
      11: ["Peace Is An Option — pacify a target's anger, gain advantage on Persuasion & Performance; cannot attack while active; if broken, target gets a free surprise reaction (no damage)", "Imaginary Weapon becomes +2"],
      12: ["Ability Score Improvement"],
      13: ["Extra Attack (2 total)"],
      14: ["Ability Score Improvement"],
      15: ["Wielding Mind — advantage on saves vs. mental effects (harder to charm)", "Imaginary Weapon becomes +3"],
      16: ["Ability Score Improvement"],
      17: ["Extra Attack (3 total)"],
      18: ["Empowered Sight — switch your vision to Truesight at will (unlimited)"],
      19: ["Ability Score Improvement", "Imaginary Weapon becomes +4"],
      20: ["Realistic — your creations no longer vanish when the ability ends; they become real objects. Requires a level-9 blank spell scroll to activate."],
    },
  },
};

export const SUBCLASSES = {
  Artificer:   ["Alchemist", "Armorer", "Artillerist", "Battle Smith"],
  Barbarian:   ["Path of the Berserker", "Path of the Wild Heart", "Path of the World Tree", "Path of the Zealot"],
  Bard:        ["College of Dance", "College of Glamour", "College of Lore", "College of Valor"],
  Cleric:      ["Life Domain", "Light Domain", "Trickery Domain", "War Domain"],
  Druid:       ["Circle of the Land", "Circle of the Moon", "Circle of the Sea", "Circle of the Stars"],
  Fighter:     ["Battle Master", "Champion", "Eldritch Knight", "Psi Warrior"],
  Monk:        ["Warrior of Mercy", "Warrior of Shadow", "Warrior of the Elements", "Warrior of the Open Hand"],
  Paladin:     ["Oath of Devotion", "Oath of Glory", "Oath of the Ancients", "Oath of Vengeance"],
  Ranger:      ["Beast Master", "Fey Wanderer", "Gloom Stalker", "Hunter"],
  Rogue:       ["Arcane Trickster", "Assassin", "Soulknife", "Swashbuckler", "Thief"],
  Sorcerer:    ["Aberrant Sorcery", "Clockwork Sorcery", "Draconic Sorcery", "Wild Magic Sorcery"],
  Warlock:     ["The Archfey", "The Celestial", "The Fiend", "The Great Old One"],
  Wizard:      ["Abjurer", "Diviner", "Evoker", "Illusionist"],
  "Omni-Knight": ["—"],
};

// Backgrounds — from the user's homebrew background.pdf.
export const BACKGROUND_INFO = {
  Acolyte: { skills: ["Insight", "Religion"], tools: [], languages: [], equipment: "Holy symbol, prayer book or prayer wheel, 5 sticks of incense, vestments, common clothes, 15 gp", description: "Bridge between the sacred and the mortal — you tend rites, guide worshippers, and uphold religious traditions." },
  Athlete: { skills: ["Acrobatics", "Athletics"], tools: ["Vehicles (land)"], languages: [], equipment: "Bronze discus or leather ball, lucky charm or trophy, traveler's clothes, 10 gp", description: "Dedicated to physical perfection and the thrill of competition." },
  "City Watch": { skills: ["Athletics", "Insight"], tools: [], languages: ["Two of your choice"], equipment: "Uniform, a horn to summon help, manacles, 10 gp", description: "A guardian of your community, protecting it from crime and maintaining order." },
  Charlatan: { skills: ["Deception", "Sleight of Hand"], tools: ["Disguise kit", "Forgery kit"], languages: [], equipment: "Fine clothes, disguise kit, con tools (weighted dice / marked cards / colored bottles / fake signet ring), 15 gp", description: "You know what people want and you promise to deliver. A silver tongue sells impossible dreams." },
  Criminal: { skills: ["Deception", "Stealth"], tools: ["Gaming set", "Thieves' tools"], languages: [], equipment: "Crowbar, dark common clothes with hood, 15 gp", description: "History of breaking the law and surviving the underworld." },
  "Folk Hero": { skills: ["Animal Handling", "Survival"], tools: ["Artisan's tools", "Vehicles (land)"], languages: [], equipment: "Artisan's tools (one), shovel, iron pot, common clothes, 10 gp", description: "Humble origins, but your deeds have made you a champion of the common folk." },
  Gambler: { skills: ["Deception", "Insight"], tools: ["One gaming set"], languages: [], equipment: "Gaming set, lucky charm, fine clothes, 15 gp", description: "You live by chance — there's always another wager." },
  Inquisitor: { skills: ["Investigation", "Religion"], tools: ["Thieves' tools", "Artisan's tools (one)"], languages: [], equipment: "Holy symbol, traveler's clothes, 15 gp", description: "A seeker of truth, trained to uncover hidden threats both mundane and supernatural." },
  Marine: { skills: ["Athletics", "Survival"], tools: ["Vehicles (water)", "Vehicles (land)"], languages: [], equipment: "Dagger of a fallen comrade, folded flag, traveler's clothes, 10 gp", description: "Hardened warrior of sea and shore." },
  Noble: { skills: ["History", "Persuasion"], tools: ["One gaming set"], languages: [], equipment: "Fine clothes, signet ring, scroll of pedigree, 25 gp", description: "Born into wealth and title — your status opens doors in high society." },
  Outlander: { skills: ["Athletics", "Survival"], tools: ["One musical instrument"], languages: [], equipment: "Staff, hunting trap, animal trophy, traveler's clothes, 10 gp", description: "Raised in the wilds — the wild is in your blood." },
  Sailor: { skills: ["Athletics", "Perception"], tools: ["Navigator's tools", "Vehicles (water)"], languages: [], equipment: "Belaying pin, 50 ft silk rope, lucky charm, common clothes, 10 gp", description: "Years aboard a seagoing vessel facing storms, sea monsters, and pirates." },
  Soldier: { skills: ["Athletics", "Intimidation"], tools: ["One gaming set", "Vehicles (land)"], languages: [], equipment: "Insignia of rank, trophy from a fallen enemy, bone dice or cards, common clothes, 10 gp", description: "War has been your life. You've trained, fought, and survived." },
  Entertainer: { skills: ["Acrobatics", "Performance"], tools: ["Disguise kit", "One musical instrument"], languages: [], equipment: "Musical instrument, favor from an admirer, costume, 15 gp", description: "You thrive in front of an audience — through music, dance, poetry, or humor." },
  "Haunted One": { skills: ["Arcana", "Investigation", "Religion", "Survival"], tools: [], languages: ["One exotic"], equipment: "Monster hunter's pack, common clothes, trinket of significance, 15 gp", description: "Something terrible haunts you — too awful to speak of, impossible to outrun." },
  "Elven Youngling": { skills: ["Arcana", "Perception"], tools: ["Artisan's tools (one)", "Musical instrument"], languages: ["One of your choice"], equipment: "Explorer's pack, elven clothes, trinket of significance, 3rd-level spell scroll, 25 gp", description: "High Elves only. Sent into the world alone, you must return only with worthy knowledge." },
  "Monster Hunter": { skills: ["Nature", "Survival"], tools: ["Herbalism kit", "Poisoner's kit"], languages: ["One Monsters language"], equipment: "Traveler's clothes, herbalism kit, monster trophy, 5 days' rations, 10 gp", description: "Your community was saved from a great beast — and you were the unlikely agent of its salvation." },
  Apprentice: { skills: ["Insight", "Performance"], tools: ["Artisan's tools matching your apprenticeship"], languages: [], equipment: "Artisan's tools matching your apprenticeship, 5 gp", description: "Years under a master — long hours, modest pay, but you have a craft." },
  Experiment: { skills: ["Deception", "History", "Investigation", "Medicine", "Perception", "Survival"], tools: ["Alchemist's supplies", "Herbalism kit", "Disguise kit", "Thieves' tools"], languages: [], equipment: "Backpack, ragged clothes, sack, crowbar or knife, lantern, oil flasks, incomplete lab notes, blanket, 50 ft rope, 5 gp", description: "The result of twisted experimentation — created, kidnapped, or modified by a master. Since escaped." },
  Slave: { skills: ["Performance", "Survival"], tools: ["Any one tool worth no more than 15 gp"], languages: [], equipment: "One tool or simple melee weapon, clothes, 1 gp", description: "Once another's property. You've found the wider world, but the weight of that past lingers." },
  Hermit: { skills: ["Medicine", "Religion"], tools: ["Herbalism kit"], languages: [], equipment: "Scroll case of notes or prayers, winter blanket, common clothes, herbalism kit, 5 gp", description: "Years in seclusion seeking answers society could never provide." },
  Bodyguard: { skills: ["Athletics", "Perception"], tools: ["One gaming set"], languages: [], equipment: "Spear, light crossbow & 20 bolts, gaming set, hooded lantern, manacles, traveler's clothes, 12 gp — or 50 gp", description: "Countless hours at your post: one eye outside the wall, the other inside." },
  "Railway Attendant": { skills: ["Insight", "Persuasion"], tools: ["Vehicles (land)", "Navigator's tools"], languages: [], equipment: "Railway uniform, conductor's whistle, route map, ticket punch or ledger, 15 gp", description: "Days aboard the rails connecting Triveor, Ank'harel, and the San'triel Forest." },
  Custom: { skills: [], tools: [], languages: [], equipment: "", description: "Your own background. Fill in the details below.", isCustom: true },
};

export const BACKGROUND_LIST = Object.keys(BACKGROUND_INFO);

export const ALIGNMENTS = [
  "Lawful Good", "Neutral Good", "Chaotic Good",
  "Lawful Neutral", "True Neutral", "Chaotic Neutral",
  "Lawful Evil", "Neutral Evil", "Chaotic Evil",
];

export const POINT_COST = { 8: 0, 9: 1, 10: 2, 11: 3, 12: 4, 13: 5, 14: 7, 15: 9 };
export const POINT_BUDGET = 27;

export const STARTING_EQUIPMENT = {
  Artificer:   ["Light Crossbow", "20 Bolts", "Studded Leather Armor", "Thieves' Tools", "Dungeoneer's Pack"],
  Barbarian:   ["Greataxe", "4 Handaxes", "Explorer's Pack"],
  Bard:        ["Rapier", "Diplomat's Pack", "Lute", "Leather Armor", "Dagger"],
  Cleric:      ["Mace", "Shield", "Chain Shirt", "Holy Symbol", "Priest's Pack"],
  Druid:       ["Scimitar", "Leather Armor", "Wooden Shield", "Druidic Focus", "Explorer's Pack"],
  Fighter:     ["Chain Mail", "Greatsword", "Flail", "8 Javelins", "Dungeoneer's Pack"],
  Monk:        ["Spear", "5 Daggers", "Explorer's Pack"],
  Paladin:     ["Chain Mail", "Shield", "Longsword", "6 Javelins", "Holy Symbol", "Priest's Pack"],
  Ranger:      ["Studded Leather Armor", "Scimitar", "Shortsword", "Longbow", "20 Arrows", "Druidic Focus", "Explorer's Pack"],
  Rogue:       ["Leather Armor", "2 Daggers", "Shortsword", "Shortbow", "20 Arrows", "Thieves' Tools", "Burglar's Pack"],
  Sorcerer:    ["Spear", "2 Daggers", "Arcane Focus", "Dungeoneer's Pack"],
  Warlock:     ["Leather Armor", "Sickle", "2 Daggers", "Arcane Focus", "Scholar's Pack", "Book of Shadows"],
  Wizard:      ["Quarterstaff", "Arcane Focus", "Spellbook", "Robe", "Scholar's Pack"],
  "Omni-Knight": ["Imaginary Weapon", "Leather Armor", "Explorer's Pack"],
};

export const ABIL_KEYS = ["str", "dex", "con", "int", "wis", "cha"];
export const ABIL_LABEL = {
  str: "Strength", dex: "Dexterity", con: "Constitution",
  int: "Intelligence", wis: "Wisdom", cha: "Charisma",
};

// Each class gets a signature accent colour for the preview-card border
// glow — a small Beyond-style flourish.
export const CLASS_ACCENT = {
  Artificer: "#c9742b", Barbarian: "#a93232", Bard: "#c08aa5",
  Cleric: "#d4b07a", Druid: "#5c8a4a", Fighter: "#8a8a8a",
  Monk: "#7da8c4", Paladin: "#e1c264", Ranger: "#4f7a4a",
  Rogue: "#5a5a5a", Sorcerer: "#b54a4a", Warlock: "#6e3a8c",
  Wizard: "#4a6a9a", "Omni-Knight": "#a87ed0",
};

export function spentPoints(abilities) {
  return ABIL_KEYS.reduce((sum, k) => sum + (POINT_COST[abilities[k]] ?? 0), 0);
}
